# Workflow derived from https://github.com/prncevince/test-workflow-restore-cache

name: restore-cache
on:
  schedule:
    - cron: '0 4 * * 0,4'
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:
jobs:
  restore-cache:
    if: github.event.schedule != ''
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        r: ['release']
        r-repo: ['https://packagemanager.rstudio.com/all/__linux__/focal/latest']
    steps:
      - name: Set restore key partials
        id: restore-partials
        run: |
          Rscript -e 'cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")'
          Rscript -e 'cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")'
      - uses: actions/checkout@v3
      - name: Restore renv cache
        uses: prncevince/actions-cache@v1.0.0
        with:
          only-restore: true
          path: ${{ runner.temp }}/renv
          key: '-'
          restore-keys: __prncevince_r-actions-rmd-site-${{ steps.restore-partials.outputs.os-version }}-${{ steps.restore-partials.outputs.r-version }}-
      - name: Restore knitr cache
        uses: prncevince/actions-cache@v1.0.0
        with:
          only-restore: true
          path: spatial-mlr3_cache
          key: '-'
          restore-keys: __prncevince_r-actions_2-rmd-site-${{ steps.restore-partials.outputs.os-version }}-${{ steps.restore-partials.outputs.r-version }}-
